# Generated by Django 4.1.2 on 2022-11-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicalName', models.CharField(max_length=50)),
                ('licenseNo', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('confirmPassword', models.CharField(max_length=50)),
                ('termsAgreement', models.BooleanField(default=False)),
            ],
        ),
    ]
